name: Docker Build

# GHCR'ye push izni ver
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ master ]

env:
  IMAGE: ghcr.io/wicknaer/juice-shop-bogazici  # tamamı lowercase olmalı

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE }}:${{ github.sha }}
