name: Docker Build

on:
  push:
    branches: [ master ]

env:
  IMAGE: ghcr.io/wicknaer/juice-shop-bogazici

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ env.IMAGE }}:latest
