name: CI - Build, SBOM & Semgrep

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-sbom-semgrep:
    name: Build, SBOM & Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Docker Build
      - name: Build Docker Image
        run: |
          docker build -t juice-shop-bogazici .

      # Syft SBOM generation
      - name: Generate SBOM with Syft
        uses: anchore/syft-action@v0.15.0
        with:
          image: juice-shop-bogazici
          format: json

      # Semgrep Scan
      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci" # popüler CI kuralları, istersen değiştirilebilir
          severity-threshold: WARNING
